export const {
  PCC_AUTH_PASSPHRASE,
  PCC_BASE_URL,
  PCC_AUTH_TOKEN,
  PCC_AUTH_PPK,
  PCC_AUTH_CERT,
  PCC_AUTH_PEM,
  CONN_STR,
  SENDGRID_API_KEY,
  INVITATION_EMAIL_TEMPLATE,
  SENDGRID_FROM_EMAIL,
  JWT_PRIVATE_KEY,
  JWT_PRIVATE_KEY_ID,
  JWT_ISSUER,
  B2C_TENANT_NAME,
  B2C_APPLICATION_ID,
  B2C_SIGNUP_POLICY,
  B2C_REDIRECT_URI,
  INVITATION_LINK,
  CERIDIAN_BASE_URL,
  CERIDIAN_API_USER,
  CERIDIAN_API_PASSWORD,
  IS_LOCAL,
} = process.env;

export const RECORD_CREATED = { message: 'Record Created!' };
export const RECORD_UPDATED = { message: 'Record Updated!' };
export const RECORD_DELETED = { message: 'Record Deleted!' };
export const EMAIL_SENT = { message: 'Email Sent!' };

export const DATE_OP = {
  ADD: 'add',
  SUBSCTRACT: 'sub',
};

export const TABLES = {
  INVITATION: 'Invitation',
  ORGANIZATION: 'Organization',
  GROUP: 'Group',
  GROUPPOLICY: 'GroupPolicy',
  GROUPUSER: 'GroupUser',
  USER: 'User',
  BATCH_PROCESS: 'BatchProcesses',
  RESIDENT: 'Resident',
  EMPLOYEE: 'Employee',
  DEPARTMENT: 'Department',
  JOB: 'Job',
  EMPLOYEE_HOUR: 'EmployeeHour',
  PAYCODE: 'Paycode',
  FACILITY: 'Facility',
};

export const INVITATION_EXPIRY_IN_DAYS = 10;
export const INVITATION_STATUS = {
  INVITED: 'INVITED',
  REGISTERED: 'REGISTERED',
  EXPIRED: 'EXPIRED',
};

export const JWT_ENCRYPTION_ALG = 'RS256';
export const JWT_EXPIRY = '10d';
export const DEFAULT_PAGE_SIZE = 200;
export const FIELDS_TO_MASK = ['json'];
export const MASKING_TEXT = '[SANITIZED]';

export const IMPORT_PATIENT_BY_FACILITY_FUNCTIONS = {
  ORCHESTRATOR: 'orchBulkImportPatientByFacility',
  IMPORT_ACTIVITY: 'actBulkImportPatient',
  UPDATE_STATUS_ACTIVITY: 'actUpdateImportStatus',
};
export const IMPORT_PATIENT_BY_ORGANIZATION_FUNCTIONS = {
  ORCHESTRATOR: 'orchBulkImportPatientByOrganization',
  RETRIEVE_FACILITY_ACTIVITY: 'actRetrieveFacilities',
  IMPORT_ACTIVITY: 'actBulkImportPatient',
  UPDATE_STATUS_ACTIVITY: 'actUpdateImportStatus',
};
export const IMPORT_EMPLOYEE_BY_ORGANIZATION_FUNCTIONS = {
  ORCHESTRATOR: 'orchBulkImportEmployeeByOrganization',
  IMPORT_ACTIVITY: 'actBulkImportEmployee',
  UPDATE_STATUS_ACTIVITY: 'actUpdateImportStatus',
};
export const IMPORT_DEPARTMENT_BY_ORGANIZATION_FUNCTIONS = {
  ORCHESTRATOR: 'orchBulkImportDepartment',
  IMPORT_ACTIVITY: 'actBulkImportDepartment',
  UPDATE_STATUS_ACTIVITY: 'actUpdateImportStatus',
};
export const IMPORT_JOB_BY_ORGANIZATION_FUNCTIONS = {
  ORCHESTRATOR: 'orchBulkImportJob',
  IMPORT_ACTIVITY: 'actBulkImportJob',
  UPDATE_STATUS_ACTIVITY: 'actUpdateImportStatus',
};
export const IMPORT_EMPLOYEE_HOURS_BY_ORGANIZATION_FUNCTIONS = {
  ORCHESTRATOR: 'orchBulkImportEmployeeHour',
  IMPORT_ACTIVITY: 'actBulkImportEmployeeHour',
  CLEAR_TRANS_IMPORT_ACTIVITY: 'actClearTransEmployeeHour',
  PROCESS_IMPORT_ACTIVITY: 'actProcessImportEmployeeHour',
  UPDATE_STATUS_ACTIVITY: 'actUpdateImportStatus',
};

export const BATCH_PROCESS_STATUS = {
  PENDING: 'Pending',
  RUNNING: 'Running',
  FAILED: 'Failed',
  COMPLETED: 'Completed',
  TERMINATED: 'Terminated',
};
export const BATCH_PROCESS_ENTITY = {
  FACILITY: 'FACILITY',
  ORGANIZATION: 'ORGANIZATION',
};
export const BATCH_PROCESS_OPERATION = {
  REFRESH_PATIENT: 'REFRESH_PATIENT',
  REFRESH_EMPLOYEE: 'REFRESH_EMPLOYEE',
  REFRESH_JOB: 'REFRESH_JOB',
  REFRESH_DEPARTMENT: 'REFRESH_DEPARTMENT',
  REFRESH_EMPLOYEE_HOUR: 'REFRESH_EMPLOYEE_HOUR',
};

export const CERIDIAN_QUERY_PARAM = {
  START_DATE: '2f23bae3-8b6f-4d71-98be-d4d90b9a2e98',
  END_DATE: 'c89de831-98f0-4cee-bc74-30b7f592236f',
};
export const CERIDIAN_PAYROLL_SYSTEM_ID = 'Ceridian';

export const DAILY_IMPORT_INVTERVAL = {
  PATIENT: 7,
  EMPLOYEE: 7,
  JOB: 7,
  DEPARTMENT: 7,
  EMPLOYEE_HOUR: 7,
};
export const FULL_IMPORT_INTERVAL = {
  PATIENT: '01/01/2020',
  EMPLOYEE: '01/01/2020',
  JOB: '01/01/2020',
  DEPARTMENT: '01/01/2020',
  EMPLOYEE_HOUR: '01/01/2020',
};
export const TIMER_IMPORT_USER_ID = 0;
export const TIMER_IMPORT_MAPPING = {
  timerPatientDailyRefresh: {
    ENTITY: 'PATIENT',
    BATCH_PROCESS_OPERATION: BATCH_PROCESS_OPERATION.REFRESH_PATIENT,
    FUNCTIONS: IMPORT_PATIENT_BY_ORGANIZATION_FUNCTIONS,
  },
  timerPatientFullRefresh: {
    ENTITY: 'PATIENT',
    BATCH_PROCESS_OPERATION: BATCH_PROCESS_OPERATION.REFRESH_PATIENT,
    FUNCTIONS: IMPORT_PATIENT_BY_ORGANIZATION_FUNCTIONS,
  },
  timerEmployeeDailyRefresh: {
    ENTITY: 'EMPLOYEE',
    BATCH_PROCESS_OPERATION: BATCH_PROCESS_OPERATION.REFRESH_EMPLOYEE,
    FUNCTIONS: IMPORT_EMPLOYEE_BY_ORGANIZATION_FUNCTIONS,
  },
  timerEmployeeFullRefresh: {
    ENTITY: 'EMPLOYEE',
    BATCH_PROCESS_OPERATION: BATCH_PROCESS_OPERATION.REFRESH_EMPLOYEE,
    FUNCTIONS: IMPORT_EMPLOYEE_BY_ORGANIZATION_FUNCTIONS,
  },
  timerJobDailyRefresh: {
    ENTITY: 'JOB',
    BATCH_PROCESS_OPERATION: BATCH_PROCESS_OPERATION.REFRESH_JOB,
    FUNCTIONS: IMPORT_JOB_BY_ORGANIZATION_FUNCTIONS,
  },
  timerJobFullRefresh: {
    ENTITY: 'JOB',
    BATCH_PROCESS_OPERATION: BATCH_PROCESS_OPERATION.REFRESH_JOB,
    FUNCTIONS: IMPORT_JOB_BY_ORGANIZATION_FUNCTIONS,
  },
  timerDepartmentDailyRefresh: {
    ENTITY: 'DEPARTMENT',
    BATCH_PROCESS_OPERATION: BATCH_PROCESS_OPERATION.REFRESH_DEPARTMENT,
    FUNCTIONS: IMPORT_DEPARTMENT_BY_ORGANIZATION_FUNCTIONS,
  },
  timerDepartmentFullRefresh: {
    ENTITY: 'DEPARTMENT',
    BATCH_PROCESS_OPERATION: BATCH_PROCESS_OPERATION.REFRESH_DEPARTMENT,
    FUNCTIONS: IMPORT_DEPARTMENT_BY_ORGANIZATION_FUNCTIONS,
  },
  timerEmployeeHourDailyRefresh: {
    ENTITY: 'EMPLOYEE_HOUR',
    BATCH_PROCESS_OPERATION: BATCH_PROCESS_OPERATION.REFRESH_EMPLOYEE_HOUR,
    FUNCTIONS: IMPORT_EMPLOYEE_HOURS_BY_ORGANIZATION_FUNCTIONS,
  },
  timerEmployeeHourFullRefresh: {
    ENTITY: 'EMPLOYEE_HOUR',
    BATCH_PROCESS_OPERATION: BATCH_PROCESS_OPERATION.REFRESH_EMPLOYEE_HOUR,
    FUNCTIONS: IMPORT_EMPLOYEE_HOURS_BY_ORGANIZATION_FUNCTIONS,
  },
};
